name: Master Deploy

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps: 
       - 
        name: Check out code
        uses: actions/checkout@v2
      - 
        name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      -
        name: Yarn
        run: yarn
      -
        name: Run Tests
        run: yarn test
      -
        name: Lint Tests 
        run: | 
          yarn lint:ts
          yarn lint:css
      - 
        name: Test Build
        run: yarn build
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - 
        name: Check out code
        uses: actions/checkout@v2
      - 
        name: Deploy to Vercel
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'